# Activation Functions
- They are mathematical functions applied to the output of a neuron or a set of neurons in a neural network.
- They introduce non-linearity to the network, allowing it to learn complex patterns and make more accurate predictions.

Maxpooling
- Pooling is a downsampling operation that reduces dimensionality of the feature map
- When performing max pooling with a 2x2 pooling window and a stride of 2, the resultant output will have dimensions that are reduced by half in both rows and columns compared to the input stride of 1 result 1 row less.

**Stride**
- A stride determines the step size or the amount by which the pooling window moves horizontally & vertically
- A stride of 1 means that the pooling window moves one unit at a time, resulting in overlapping regions
- A stride of 2 means that the pooling window moves two units at a time, resulting in non-overlapping regions.

**Window size**
- Determines the size of the regions over which the maximum value is computed.
- In average pooling, the window size determines the size of the regions over which the average value is calculated.
- Common window sizes are 2x2 or 3x3, but other sizes can also be used.

In [1]:
import numpy as np

# Input matrix
input_matrix = np.array([[1, 2, 3, 4, 5, 6],
                         [7, 8, 9, 10, 11, 12],
                         [13, 14, 15, 16, 17, 18],
                         [19, 20, 21, 22, 23, 24]])

# Pooling window size and stride
window_size = (2, 2)
stride = (1, 1)

# Compute output shape
output_shape = ((input_matrix.shape[0] - window_size[0]) // stride[0] + 1,
                (input_matrix.shape[1] - window_size[1]) // stride[1] + 1)

# Initialize output matrix
output_matrix = np.zeros(output_shape)

# Perform max pooling
for i in range(output_shape[0]):
    for j in range(output_shape[1]):
        window = input_matrix[i:i+window_size[0], j:j+window_size[1]]
        output_matrix[i, j] = np.max(window)

print("Input Matrix:")
print(input_matrix)
print("\nOutput Matrix (Max Pooling):")
print(output_matrix)

Input Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Output Matrix (Max Pooling):
[[ 8.  9. 10. 11. 12.]
 [14. 15. 16. 17. 18.]
 [20. 21. 22. 23. 24.]]
